---
title: "Rubric"
format: html
editor: visual
---

### **Applied Bayesian Modeling for Natural Resource Management Project Rubric**

Total points remaining: 45

Presentation points: 22.5

Write up points: 22.5

The 22.5 points will be weighted equally among the criteria in the first column, with both the project presentations and write-ups judged by the same criteria:

|                       |                                                                                                                                                                                                 |                                                                                                                                            |                                                                                                         |                                                                                               |
|-----------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
|  **Criteria**         |  **Excellent**                                                                                                                                                                                  |  **Proficient**                                                                                                                            |  **Basic**                                                                                              |  **Below Expectations**                                                                       |
|  **Content**          | Demonstrates a strong understanding of Bayesian concepts, with a comprehensive and well-supported application of statistical methods.                                                           |  Conveys a satisfactory grasp of Bayesian principles with clear and well-supported statistical content.                                    |  Provides basic application of Bayesian concepts but may lack depth or thorough support.                |  Contains inaccurate or incomplete use of Bayesian statistics.                                |
|  **Clarity**          |  Presents ideas and statistical results in a clear, organized, and easily understandable manner, with effective communication of probabilistic concepts.                                        |  Communicates effectively with clarity, but may have occasional instances of confusion in conveying concepts.                              |  Contains some unclear or confusing elements, making it challenging to follow reasoning.                |  Lacks coherence in presenting concepts, making understanding difficult.                      |
|  **Methodology**      |  Clearly outlines a well-thought-out and robust Bayesian methodology, demonstrating a systematic and appropriate approach to statistical modeling and inference.                                |  Provides a sound Bayesian methodology, but some aspects may be underdeveloped or unclear in terms of modeling and inference.              |  Includes a basic methodology, but lacks detail or a clear plan for statistical modeling.               |  Methodology is unclear, incomplete, or significantly flawed in terms of Bayesian principles. |
|  **Model Evaluation** |  Demonstrates a comprehensive and effective evaluation of Bayesian model outcomes, using appropriate methods and justification of model components (like the choice of priors and likelihoods). |  Conducts a thorough evaluation of Bayesian results, but some aspects may be less detailed or miss key points in justifying model choices. |  Conducts a basic evaluation but lacks depth or may not cover all relevant aspects of model assessment. |  Evaluation is unclear, incomplete, or does not align with the project's objectives.          |
