---
title: Hierarchical stock-recruitment modeling
subtitle: 10 total points
author: Christopher Cahill
date: 27 October 2023
date-format: "D MMMM YYYY"
format: 
  pdf: default
---

## NOTE: date above is the due date

### Background
 
 The relationship between stock or spawning stock biomass and recruitment is perhaps the most important relationship in fisheries science.  In age- or stage-structured fisheries population models this relationship describes the maximum expected recruitment rate and the degree of density dependence in recruitment. 

 There are more than 70 species of rockfish *Sebastes* spp. off the coast of western North America from the Gulf of California to the Bering Sea.  Rockfish are infrequently caught, difficult to tell apart, and commercially valuable.  Rockfish are are also delectable in omlettes when served with a tasty beer on a rainy morning in Seattle.  Because they are tasty, there is also a great deal of concern about Rockfish conservation.  Previous West Coast rockfish analyses suggest low productivity compared with other fish stocks, but these analyses remain hampered by a scarcity of reliable, fishery-independent data, the short time span of the data that have been collected, and the apparent variability within those data.
 
 In this assignment, your goal is to estimate stock-recruitment relationships for a subset of these species by sharing information about stock-recruit $\alpha$ across the species complex using a hierarchical model (see model details below). In essence, you are trying to steal from the information rich species to give to the information poor stocks.  The results from your analysis will be used to set informative priors for stock-recruitment $\alpha$ in future Rockfish stock assessments.  The reason you are interested in among-species variation in $\alpha$ is because it describes the maximum recruitment potential in response to reductions in the density of spawners due to fishing and thus is directly correlated with the maximum sustainable exploitation rate $U_{MSY}$.  Consequently, estimating $\alpha$ should provide insights into the resilience of different rockfishes to exploitation (see also Dorn 2002).  

The Ricker stock-recruitment model can be parameterized as:  
$$
R_{t}=\frac{\alpha}{sbro} \cdot SSB_{t} \cdot e^{-\beta \cdot SSB_{t}}
$$

where 

  - $R_{t}$ is recruitment in year t
  - $SSB_{t}$ is spawning stock biomass in year t
  - $sbro$ is spawner biomass per recruit in the unfished condition (no exploitation)
  - $\alpha$ , $\beta$ are the parameters of the stock-recruitment relationship 

Your task is to develop a (linear) Bayesian hierarchical stock-recruitment model for 11 West Coast Rockfish species using Stan (see 'rockfish.csv' in the data folder).  Treat $ln(\alpha)$ as a normally distributed random effect and $\beta$ as fixed effects. Assume that noise about the stock recruitment relationship is lognormal, and that this noise is similar among species.  Evaluate your model.  

Beyond the details given above, you have some freedom in terms of how you specify your model.  Choose reasonable priors for $\beta$, your hyperpriors for $ln(\alpha)$, and the likelihood error term.

1. What is your interpretation of your model's fit and its ability to inform management or future stock assessments?
2. Which species or stock is has the most(least) resilience to harvest? 
3. Which species or stock has the most uncertainty about $ln(\alpha)$ ? 
4. How might you try to improve your model in the future? 

## References:

Dorn, M. 2002.  Advice on West Coast rockfish harvest rates from Bayesian meta-analysis of stock− recruit relationships.  North American Journal of Fisheries Management.


